#!/bin/bash 

OUTPUT_DIRECTORY="swift"

mkdir -p $OUTPUT_DIRECTORY
rm -rf $OUTPUT_DIRECTORY/*

for MODULE in $(cat swift.txt)
do
    MODULE_DIRECTORY="$OUTPUT_DIRECTORY/$MODULE"
    mkdir -p $MODULE_DIRECTORY
    swift-symbolgraph-extract -skip-inherited-docs \
        -output-dir $MODULE_DIRECTORY \
        -target x86_64-unknown-linux-gnu \
        -module-name $MODULE
done
